"""Multi-agent pipeline demo.

Simulates a three-agent system:
  PlannerAgent  →  ResearcherAgent  →  WriterAgent

Demonstrates:
- Multiple @agentlens.trace() calls producing separate traces
- Handoff spans connecting agents in the topology graph
- Different LLM models with distinct cost profiles
- agentlens.log() for structured event messages inside spans
"""
import time

import agentlens

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
agentlens.configure(server_url="http://localhost:3000")


# ---------------------------------------------------------------------------
# Simulated helpers
# ---------------------------------------------------------------------------

def _sleep(s: float) -> None:
    """Short sleep to simulate real work durations."""
    time.sleep(s)


def _fake_plan(topic: str) -> list[str]:
    _sleep(0.8)
    return [
        f"1. Search arXiv for recent papers on '{topic}'",
        "2. Search the web for practitioner blog posts",
        "3. Synthesize findings into a structured report",
    ]


def _fake_arxiv_search(query: str) -> str:
    _sleep(1.2)
    return (
        "arXiv results: [2401.12345] 'Efficient Attention via Sparse Patterns' — "
        "[2402.09876] 'Mixture-of-Experts at Scale' — "
        "[2403.11111] 'In-Context Learning Survey'"
    )


def _fake_web_search(query: str) -> str:
    _sleep(0.9)
    return (
        "Web results: Andrej Karpathy blog — 'The State of LLM Tooling 2024'; "
        "Hugging Face blog — 'Open LLMs are Catching Up'; "
        "Simon Willison — 'Prompting as a skill'"
    )


def _fake_synthesize(arxiv: str, web: str) -> str:
    _sleep(1.5)
    return (
        "Synthesized findings: Sparse attention and MoE architectures are the dominant "
        "efficiency trends. Open-source models (Mistral, Llama 3) are narrowing the gap "
        "with GPT-4 on benchmarks. Prompting craft remains a key differentiator."
    )


def _fake_draft_report(findings: str, tasks: list[str]) -> str:
    _sleep(2.0)
    return (
        "# AI Research Report\n\n"
        "## Executive Summary\n"
        f"{findings}\n\n"
        "## Key Themes\n"
        "- Efficiency: Sparse attention, MoE\n"
        "- Open-source momentum: Llama 3, Mistral\n"
        "- Tooling maturity: Prompting, RAG, agents\n"
    )


def _fake_format_markdown(report: str) -> str:
    _sleep(0.5)
    # Simulate minor markdown formatting cleanup
    return report.strip() + "\n\n*Generated by WriterAgent — AgentLens demo*\n"


# ---------------------------------------------------------------------------
# Agent 1: PlannerAgent
# Plans the research task and hands off to ResearcherAgent.
# ---------------------------------------------------------------------------

@agentlens.trace(name="PlannerAgent")
def run_planner(topic: str) -> list[str]:
    """Breaks the research topic into structured subtasks."""

    # LLM call: generate a task plan
    with agentlens.span("plan_tasks", "llm_call") as s:
        agentlens.log("Planning research strategy", topic=topic, model="gpt-4o")
        tasks = _fake_plan(topic)
        s.set_output(str(tasks))
        s.set_cost("gpt-4o", input_tokens=310, output_tokens=95)
        print(f"  [PlannerAgent] plan_tasks done — {len(tasks)} tasks")

    # Handoff span signals the topology graph to draw an edge to ResearcherAgent
    with agentlens.span("handoff_to_researcher", "handoff") as s:
        agentlens.log("Delegating to ResearcherAgent", tasks=tasks)
        s.set_output("ResearcherAgent queued with task list")
        _sleep(0.2)
        print("  [PlannerAgent] handoff_to_researcher done")

    return tasks


# ---------------------------------------------------------------------------
# Agent 2: ResearcherAgent
# Executes the search tasks and synthesizes findings.
# ---------------------------------------------------------------------------

@agentlens.trace(name="ResearcherAgent")
def run_researcher(tasks: list[str], topic: str) -> str:
    """Runs searches and synthesizes findings for the WriterAgent."""

    # Tool call: arXiv search
    with agentlens.span("search_arxiv", "tool_call") as s:
        agentlens.log("Querying arXiv API", query=topic)
        arxiv_results = _fake_arxiv_search(topic)
        s.set_output(arxiv_results)
        print(f"  [ResearcherAgent] search_arxiv done")

    # Tool call: web search
    with agentlens.span("search_web", "tool_call") as s:
        agentlens.log("Querying web search engine", query=topic)
        web_results = _fake_web_search(topic)
        s.set_output(web_results)
        print(f"  [ResearcherAgent] search_web done")

    # LLM call: synthesize findings — uses Claude for higher quality synthesis
    with agentlens.span("synthesize_findings", "llm_call") as s:
        agentlens.log("Synthesizing search results", model="claude-3-5-sonnet-20241022")
        findings = _fake_synthesize(arxiv_results, web_results)
        s.set_output(findings)
        s.set_cost("claude-3-5-sonnet-20241022", input_tokens=1450, output_tokens=280)
        print(f"  [ResearcherAgent] synthesize_findings done — cost tracked")

    return findings


# ---------------------------------------------------------------------------
# Agent 3: WriterAgent
# Drafts and formats the final report.
# ---------------------------------------------------------------------------

@agentlens.trace(name="WriterAgent")
def run_writer(findings: str, tasks: list[str]) -> str:
    """Drafts and formats the research report."""

    # LLM call: draft the report — uses GPT-4o-mini (cheaper, sufficient for formatting)
    with agentlens.span("draft_report", "llm_call") as s:
        agentlens.log("Drafting report structure", model="gpt-4o-mini")
        draft = _fake_draft_report(findings, tasks)
        s.set_output(draft[:500])
        s.set_cost("gpt-4o-mini", input_tokens=920, output_tokens=410)
        print(f"  [WriterAgent] draft_report done — cost tracked")

    # Tool call: format markdown
    with agentlens.span("format_markdown", "tool_call") as s:
        agentlens.log("Applying markdown formatting rules")
        final_report = _fake_format_markdown(draft)
        s.set_output(final_report[:300])
        print(f"  [WriterAgent] format_markdown done")

    return final_report


# ---------------------------------------------------------------------------
# Pipeline orchestrator — runs all three agents in sequence.
# ---------------------------------------------------------------------------

def run_pipeline(topic: str) -> str:
    """Orchestrate the full PlannerAgent → ResearcherAgent → WriterAgent pipeline."""
    print(f"\nTopic: '{topic}'")

    print("\n[1/3] PlannerAgent running...")
    tasks = run_planner(topic)

    print("\n[2/3] ResearcherAgent running...")
    findings = run_researcher(tasks, topic)

    print("\n[3/3] WriterAgent running...")
    report = run_writer(findings, tasks)

    return report


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    topic = "Efficient Large Language Model architectures in 2024"
    report = run_pipeline(topic)

    print("\n" + "=" * 55)
    print("Pipeline complete. Final report preview:")
    print("-" * 55)
    print(report[:400])
    print("\n3 traces sent to AgentLens — open http://localhost:3000")
    print("Each agent appears as a separate trace in the dashboard.")
